# Generated by Django 6.0.1 on 2026-02-09 00:52

from datetime import timedelta

from django.db import migrations


def get_week_start(date):
    """Get Monday of the week containing the given date"""
    return date - timedelta(days=date.weekday())


def populate_weekly_timesheets(apps, schema_editor):
    """Create WeeklyTimesheet records for existing TimeEntry records"""
    TimeEntry = apps.get_model("timesheet", "TimeEntry")
    WeeklyTimesheet = apps.get_model("timesheet", "WeeklyTimesheet")

    # Get all time entries grouped by user
    entries = TimeEntry.objects.all().order_by("user", "date")

    # Track created weekly timesheets to avoid duplicates
    weekly_timesheets_cache = {}

    for entry in entries:
        week_start = get_week_start(entry.date)
        week_end = week_start + timedelta(days=6)

        # Create cache key
        cache_key = (entry.user_id, week_start)

        # Get or create weekly timesheet
        if cache_key not in weekly_timesheets_cache:
            weekly_timesheet, created = WeeklyTimesheet.objects.get_or_create(
                user=entry.user,
                week_start_date=week_start,
                defaults={"week_end_date": week_end, "status": "DRAFT"},
            )
            weekly_timesheets_cache[cache_key] = weekly_timesheet
        else:
            weekly_timesheet = weekly_timesheets_cache[cache_key]

        # Link entry to weekly timesheet
        entry.weekly_timesheet = weekly_timesheet
        entry.save()


def reverse_populate(apps, schema_editor):
    """Remove weekly timesheet links"""
    TimeEntry = apps.get_model("timesheet", "TimeEntry")
    TimeEntry.objects.all().update(weekly_timesheet=None)


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0003_weeklytimesheet_timeentry_weekly_timesheet"),
    ]

    operations = [
        migrations.RunPython(populate_weekly_timesheets, reverse_populate),
    ]
